[build]
publish = "public"
command = "./stackbit-build.sh"
functions = "./lambda"

[[redirects]]
  from = "/blog/*"
  to = "/index.html"
  status = 302
  force = false
  conditions = {Role = ["member"]}