[build]
publish = "public"
command = "./stackbit-build.sh"
functions = "./lambda"

[[redirects]]
from = "/blog/*"
to = "/blog/index.html"
status = 200
force = true
conditions = {Role = ["member"]}
[[redirects]]
from = "/blog/*"
to = "/index.html"
status = 302
force = true