[build]
publish = "public"
command = "./stackbit-build.sh"
functions = "./lambda"

[[redirects]]
  from = "/portfolio/"
  to = "/index.html"
  status = 302
  force = false
  conditions = {role = "member"}